/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/game/": {
    get: operations["api_game_list"];
    post: operations["api_game_create"];
  };
  "/api/game/{id}/": {
    get: operations["api_game_retrieve"];
  };
  "/api/game/{id}/join/": {
    post: operations["api_game_join_create"];
  };
  "/api/game/{id}/leave/": {
    post: operations["api_game_leave_create"];
  };
  "/api/game/{id}/start/": {
    post: operations["api_game_start_create"];
  };
  "/api/game/{id}/turn/": {
    post: operations["api_game_turn_create"];
  };
  "/api/schema/": {
    /**
     * @description OpenApi3 schema for this API. Format can be selected via content negotiation.
     *
     * - YAML: application/vnd.oai.openapi
     * - JSON: application/vnd.oai.openapi+json
     */
    get: operations["api_schema_retrieve"];
  };
  "/api/users/": {
    get: operations["api_users_list"];
  };
  "/api/users/{username}/": {
    get: operations["api_users_retrieve"];
    put: operations["api_users_update"];
    patch: operations["api_users_partial_update"];
  };
  "/api/users/me/": {
    get: operations["api_users_me_retrieve"];
  };
  "/auth-token/": {
    post: operations["auth_token_create"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    AuthToken: {
      username: string;
      password: string;
      token: string;
    };
    CreateGame: {
      settings: components["schemas"]["ShiritoriGameSettings"];
    };
    /** @enum {string} */
    LocaleEnum: "en";
    PatchedUser: {
      /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
      username?: string;
      /** Name of User */
      name?: string;
      /** Format: uri */
      url?: string;
    };
    ShiritoriGame: {
      id: string;
      settings: components["schemas"]["ShiritoriGameSettings"];
      player_count: number;
      word_count: number;
      is_finished: boolean;
      winner: components["schemas"]["ShiritoriPlayer"];
      current_player: components["schemas"]["ShiritoriPlayer"];
      turn_time_left: number;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
      status?: components["schemas"]["StatusEnum"];
      current_turn?: number;
      last_word?: string | null;
    };
    ShiritoriGameSettings: {
      locale?: components["schemas"]["LocaleEnum"];
      word_length?: number;
      turn_time?: number;
      max_turns?: number;
    };
    ShiritoriPlayer: {
      id: string;
      name: string;
      score: number;
    };
    ShiritoriTurn: {
      word: string;
      duration: number;
    };
    /** @enum {string} */
    StatusEnum: "WAITING" | "PLAYING" | "FINISHED";
    User: {
      /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
      username: string;
      /** Name of User */
      name?: string;
      /** Format: uri */
      url: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export interface operations {
  api_game_list: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["ShiritoriGame"][];
        };
      };
    };
  };
  api_game_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateGame"];
        "application/x-www-form-urlencoded": components["schemas"]["CreateGame"];
        "multipart/form-data": components["schemas"]["CreateGame"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["ShiritoriGame"];
        };
      };
    };
  };
  api_game_retrieve: {
    parameters: {
      /** @description A unique value identifying this game. */
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["ShiritoriGame"];
        };
      };
    };
  };
  api_game_join_create: {
    parameters: {
      /** @description A unique value identifying this game. */
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ShiritoriPlayer"];
        "application/x-www-form-urlencoded": components["schemas"]["ShiritoriPlayer"];
        "multipart/form-data": components["schemas"]["ShiritoriPlayer"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["ShiritoriPlayer"];
        };
      };
    };
  };
  api_game_leave_create: {
    parameters: {
      /** @description A unique value identifying this game. */
      path: {
        id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["ShiritoriGame"];
        "application/x-www-form-urlencoded": components["schemas"]["ShiritoriGame"];
        "multipart/form-data": components["schemas"]["ShiritoriGame"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["ShiritoriGame"];
        };
      };
    };
  };
  api_game_start_create: {
    parameters: {
      /** @description A unique value identifying this game. */
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ShiritoriTurn"];
        "application/x-www-form-urlencoded": components["schemas"]["ShiritoriTurn"];
        "multipart/form-data": components["schemas"]["ShiritoriTurn"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["ShiritoriTurn"];
        };
      };
    };
  };
  api_game_turn_create: {
    parameters: {
      /** @description A unique value identifying this game. */
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ShiritoriTurn"];
        "application/x-www-form-urlencoded": components["schemas"]["ShiritoriTurn"];
        "multipart/form-data": components["schemas"]["ShiritoriTurn"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["ShiritoriTurn"];
        };
      };
    };
  };
  api_schema_retrieve: {
    /**
     * @description OpenApi3 schema for this API. Format can be selected via content negotiation.
     *
     * - YAML: application/vnd.oai.openapi
     * - JSON: application/vnd.oai.openapi+json
     */
    parameters: {
      query: {
        format?: "json" | "yaml";
        lang?:
          | "af"
          | "ar"
          | "ar-dz"
          | "ast"
          | "az"
          | "be"
          | "bg"
          | "bn"
          | "br"
          | "bs"
          | "ca"
          | "cs"
          | "cy"
          | "da"
          | "de"
          | "dsb"
          | "el"
          | "en"
          | "en-au"
          | "en-gb"
          | "eo"
          | "es"
          | "es-ar"
          | "es-co"
          | "es-mx"
          | "es-ni"
          | "es-ve"
          | "et"
          | "eu"
          | "fa"
          | "fi"
          | "fr"
          | "fy"
          | "ga"
          | "gd"
          | "gl"
          | "he"
          | "hi"
          | "hr"
          | "hsb"
          | "hu"
          | "hy"
          | "ia"
          | "id"
          | "ig"
          | "io"
          | "is"
          | "it"
          | "ja"
          | "ka"
          | "kab"
          | "kk"
          | "km"
          | "kn"
          | "ko"
          | "ky"
          | "lb"
          | "lt"
          | "lv"
          | "mk"
          | "ml"
          | "mn"
          | "mr"
          | "ms"
          | "my"
          | "nb"
          | "ne"
          | "nl"
          | "nn"
          | "os"
          | "pa"
          | "pl"
          | "pt"
          | "pt-br"
          | "ro"
          | "ru"
          | "sk"
          | "sl"
          | "sq"
          | "sr"
          | "sr-latn"
          | "sv"
          | "sw"
          | "ta"
          | "te"
          | "tg"
          | "th"
          | "tk"
          | "tr"
          | "tt"
          | "udm"
          | "uk"
          | "ur"
          | "uz"
          | "vi"
          | "zh-hans"
          | "zh-hant";
      };
    };
    responses: {
      200: {
        content: {
          "application/vnd.oai.openapi": {
            [key: string]: unknown | undefined;
          };
          "application/yaml": {
            [key: string]: unknown | undefined;
          };
          "application/vnd.oai.openapi+json": {
            [key: string]: unknown | undefined;
          };
          "application/json": {
            [key: string]: unknown | undefined;
          };
        };
      };
    };
  };
  api_users_list: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["User"][];
        };
      };
    };
  };
  api_users_retrieve: {
    parameters: {
      path: {
        username: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
    };
  };
  api_users_update: {
    parameters: {
      path: {
        username: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["User"];
        "application/x-www-form-urlencoded": components["schemas"]["User"];
        "multipart/form-data": components["schemas"]["User"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
    };
  };
  api_users_partial_update: {
    parameters: {
      path: {
        username: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedUser"];
        "application/x-www-form-urlencoded": components["schemas"]["PatchedUser"];
        "multipart/form-data": components["schemas"]["PatchedUser"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
    };
  };
  api_users_me_retrieve: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
    };
  };
  auth_token_create: {
    requestBody: {
      content: {
        "application/x-www-form-urlencoded": components["schemas"]["AuthToken"];
        "multipart/form-data": components["schemas"]["AuthToken"];
        "application/json": components["schemas"]["AuthToken"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["AuthToken"];
        };
      };
    };
  };
}
