# Generated by Django 4.2 on 2023-04-03 23:13

import django.core.validators
from django.db import migrations, models
from django.db.models.functions import Left


def truncate_usernames(apps, schema_editor):
    Player = apps.get_model("game", "Player")
    Player.objects.all().update(name=Left("name", 15))


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamesettings",
            name="turn_time",
            field=models.IntegerField(
                default=60,
                validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(120)],
            ),
        ),
        migrations.RunPython(truncate_usernames, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="player",
            name="name",
            field=models.CharField(max_length=15),
        ),
    ]
