# Generated by Django 4.2 on 2023-04-04 00:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0002_alter_gamesettings_turn_time_alter_player_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="is_connected",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="name",
            field=models.CharField(
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator("^[0-9a-zA-Z]*$", "Only alphanumeric characters are allowed.")
                ],
            ),
        ),
    ]
