# Generated by Django 4.2 on 2023-04-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0003_player_is_connected_alter_player_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="task_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
