# Generated by Django 4.2 on 2023-04-29 03:04

from django.db import migrations, models


def fix_player_order(apps, _):
    # We can't import the Player model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Game = apps.get_model("game", "Game")
    # Loop over all games and assign an order to all players
    for game in Game.objects.all():
        for index, player in enumerate(game.player_set.all()):
            player.order = index
            player.save()


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0004_game_task_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="current_round",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="player",
            name="order",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunPython(fix_player_order),
        migrations.AddConstraint(
            model_name="player",
            constraint=models.UniqueConstraint(
                condition=models.Q(("order__isnull", False)), fields=("game", "order"), name="unique_order"
            ),
        ),
    ]
